Add new feature
ellaluda/tspp pull request #1
Opened 2024-09-22 17:57 UTC by ellaluda

2024-09-23 23:48 UTC, dimlichmanov commented
Удалите приватный ключ. Задание зачтено!

2024-09-23 23:48 UTC, dimlichmanov requested changes

2024-09-23 23:48 UTC, dimlichmanov commented on github
> +-----BEGIN OPENSSH PRIVATE KEY-----
Приватную часть ключа никому не сообщайте!

2024-09-24 17:31 UTC, dimlichmanov commented
А публичный ключ (.pub) оставьте, или продублируйте на почту

2024-09-24 17:38 UTC, ellaluda commented on github
> +-----BEGIN OPENSSH PRIVATE KEY-----
Уже удалила. Спасибо за ваше напоминание!

2024-09-25 06:12 UTC, ellaluda commented
> А публичный ключ (.pub) оставьте, или продублируйте на почту

Добавила публичный ключ.

2024-09-25 16:33 UTC, dimlichmanov approved these changes

2024-09-28 06:57 UTC, merged