Sem3
ellaluda/tspp pull request #5
Opened 2024-10-13 16:58 UTC by ellaluda

Пожалуйста, проверьте задание 3.

2024-10-13 17:02 UTC, dimlichmanov requested changes
В остальном код и отчёт хорошие.

2024-10-13 17:02 UTC, dimlichmanov commented on papi.cpp
> +    CHECK_PAPI_ERROR(PAPI_event_name_to_code("PAPI_TOT_INS", &code), "PAPI_TOT_INS code conversion");
PAPI_TOT_INS это **не** native event, это preset event.
Вам нужен event из выдачи papi_native_avail.

2024-10-14 11:01 UTC, ellaluda commented on papi.cpp
> +    CHECK_PAPI_ERROR(PAPI_event_name_to_code("PAPI_TOT_INS", &code), "PAPI_TOT_INS code conversion");
Я уже закончила редактирование кода и обновила результаты в отчёте.

2024-10-15 15:46 UTC, dimlichmanov approved these changes

2024-10-15 15:48 UTC, dimlichmanov commented
Задание зачтено. Закройте все PR, пожалуйста.

2024-10-16 05:23 UTC, closed without merging