Sem4
ellaluda/tspp pull request #6
Opened 2024-10-20 07:15 UTC by ellaluda

Пожалуйста, проверьте мое задание 4.

2024-10-20 08:21 UTC, dimlichmanov requested changes
1) не вносите в коммит бинарные файлы, .idea и прочие файлы, не являющиеся кодом программы или отчётом, пожалуйста
2) я посмотрел AVX-версию вашей программы, в ней есть ошибки, и разница между полученными элементами очень большая. Более того, valgrind также показал ошибки, связанные с функцией matrixMultiplyAVX. 

Попробуйте убрать шаг по 8 (для i) (или векторизовать его)
Сейчас получается, что вы пытаетесь сделать "векторизацию" два раза (одну через развёртку цикла по 8, другую явно через интринсики).

2024-10-20 12:06 UTC, ellaluda commented
> 1. не вносите в коммит бинарные файлы, .idea 和 прочие файлы, не являющиеся кодом программы или отчётом, пожалуйста
> 2. япосмотрел AVX-версию вашей програмы, в ней есть ошибки, и разница между полученными элементами очень большая.因此，valgrind 可以使用矩阵乘法 AVX。
> 
> Попробуйте убрать шаг по 8 (для i) (или векторизовать его) Сейчас получается, что вы пытаетесь сделать "векторизацию" два р аза（одну через развёртку цикла по 8，другую явно через интринсики）。

Уже исправлено, пожалуйста, проверьте.

2024-10-26 12:46 UTC, dimlichmanov requested changes
![изображение](https://github.com/user-attachments/assets/5421a3c7-a6fb-45dd-93e8-80f24a9f50ee)

2024-10-26 12:46 UTC, dimlichmanov commented
У меня при изменённой инициализации программа работает, но ошибка слишком большая.

2024-10-26 12:50 UTC, dimlichmanov commented
Ну и ускорения относительно последовательной версии нет.

2024-10-26 13:09 UTC, ellaluda commented
<img width="509" alt="截屏2024-10-26 21 06 05" src="https://github.com/user-attachments/assets/9f43f77e-815e-469e-a419-2e16c3796962">
Я изменила инициализацию матриц A и B так, чтобы ошибка была сведена к нулю. Может быть, вы сможете запустить последнюю версию, которую я загрузил?

2024-10-26 13:19 UTC, ellaluda commented
![截图 2024-10-26 21-16-11](https://github.com/user-attachments/assets/15267f41-6ba1-4ae7-99e9-31814f0c01bc)
Я запустила его снова, и максимальная ошибка равна 0.

2024-10-26 14:25 UTC, dimlichmanov commented
> Я изменила инициализацию матриц A и B так, чтобы ошибка была сведена к нулю
Чем ближе к 0 значения, ошибка будет также стремиться к 0 (у нас же умножение). Вы же не будете в реальных приложениях стабильно ставить значения, близкие к нулю.

у меня, например, maxError стабильно обновляется на 1024-ом элементе при запуске с N=1024.
Я делал инициализацию через rand()/RAND_MAX
Посмотрите, в чём может быть ошибка. Не поймёте - будем вместе смотреть. Ускорение, кстати, получил, собрал, как вы и указали, с -O3.

2024-12-27 18:40 UTC, ellaluda commented
Я изменила способ broadcast в файле vector_avx.cpp, использовала выравненный аллокатор для выделения памяти и инициализировала результирующую матрицу нулями, но всё же остались некоторые ошибки: при N=512 ошибка составляет 0.252424, и с увеличением N ошибка уменьшается — при N=1024 ошибка составляет 0.119522, а при N=2048 — 0.119447. Как вы считаете, это приемлемо?

2024-12-27 18:40 UTC, ellaluda commented
> > Я изменила инициализацию матриц A и B так, чтобы ошибка была сведена к нулю
> > Чем ближе к 0 значения, ошибка будет также стремиться к 0 (у нас же умножение). Вы же не будете в реальных приложениях стабильно ставить значения, близкие к нулю.
> 
> у меня, например, maxError стабильно обновляется на 1024-ом элементе при запуске с N=1024. Я делал инициализацию через rand()/RAND_MAX Посмотрите, в чём может быть ошибка. Не поймёте - будем вместе смотреть. Ускорение, кстати, получил, собрал, как вы и указали, с -O3.


Я изменила способ broadcast в файле vector_avx.cpp, использовала выравненный аллокатор для выделения памяти и инициализировала результирующую матрицу нулями, но всё же остались некоторые ошибки: при N=512 ошибка составляет 0.252424, и с увеличением N ошибка уменьшается — при N=1024 ошибка составляет 0.119522, а при N=2048 — 0.119447. Как вы считаете, это приемлемо?

2024-12-29 10:41 UTC, dimlichmanov approved these changes

2024-12-30 20:01 UTC, closed without merging