Sem7
ellaluda/tspp pull request #9
Opened 2024-11-12 00:29 UTC by ellaluda

Пожалуйста, проверьте задание 7.

2024-11-13 14:52 UTC, dimlichmanov requested changes
.

2024-11-13 14:52 UTC, dimlichmanov commented on task.c
> +        update_grid(curr_grid, next_grid, rows, columns);
Вы сначала обновляетесь на итерации, затем делаете пересылки - это неверно
Сначала нужно обменяться граничными элементами, затем выполнить итерацию якоби.

2024-12-30 06:05 UTC, ellaluda commented on task.c
> +        update_grid(curr_grid, next_grid, rows, columns);
Я завершила внесение изменений, пожалуйста, проверьте.

2024-12-30 06:21 UTC, dimlichmanov approved these changes

2024-12-30 19:59 UTC, closed without merging